// @ts-nocheck
import * as __fd_glob_75 from "../content/docs/style/ui-dsl.mdx?collection=docs"
import * as __fd_glob_74 from "../content/docs/style/tokens.mdx?collection=docs"
import * as __fd_glob_73 from "../content/docs/style/theme.mdx?collection=docs"
import * as __fd_glob_72 from "../content/docs/style/motion.mdx?collection=docs"
import * as __fd_glob_71 from "../content/docs/style/core-primitives.mdx?collection=docs"
import * as __fd_glob_70 from "../content/docs/migration/migration-0-2-4.mdx?collection=docs"
import * as __fd_glob_69 from "../content/docs/migration/migration-0-2-3.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/migration/migration-0-2-2.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/migration/migration-0-2-1.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/migration/migration-0-2-0.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/migration/migration-0-1-9.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/migration/migration-0-1-8.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/migration/migration-0-1-7.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/migration/migration-0-1-6.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/migration/migration-0-1-11.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/migration/migration-0-1-10.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/migration/index.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/fundamentals/workflow.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/fundamentals/testing.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/fundamentals/state-management.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/fundamentals/reactivity.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/fundamentals/reactive-engine.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/fundamentals/performance.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/fundamentals/fluxy-core.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/fundamentals/dependency-injection.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/fundamentals/data-layer.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/fundamentals/core-concepts.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/fundamentals/cli.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/fundamentals/architecture.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/layout/safe-ui.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/layout/responsive-design.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/layout/responsive-concepts.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/layout/layout-spacing.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/layout/alignment.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/forms/input.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/forms/form.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/forms/dropdown.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/forms/checkbox-switcher.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/ecosystem/routing.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/ecosystem/roadmap.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/ecosystem/play.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/ecosystem/ota-engine.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/ecosystem/networking.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/ecosystem/i18n.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/ecosystem/examples.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/ecosystem/devtools.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/ecosystem/cloud-builds.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/feedback/toast.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/feedback/modal.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/feedback/loader.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/feedback/dialog.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/feedback/badge.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/table.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/tab-scaffold.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/shimmer.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/layout.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/image.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/grid.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/dashboard.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/chart.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/button.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/bottom-bar.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/avatar.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/why-fluxy.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/quick-start.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/installation.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/style/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/migration/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/layout/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/fundamentals/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/forms/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/feedback/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/components/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/ecosystem/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "ecosystem/meta.json": __fd_glob_1, "components/meta.json": __fd_glob_2, "feedback/meta.json": __fd_glob_3, "forms/meta.json": __fd_glob_4, "fundamentals/meta.json": __fd_glob_5, "layout/meta.json": __fd_glob_6, "migration/meta.json": __fd_glob_7, "style/meta.json": __fd_glob_8, }, {"index.mdx": __fd_glob_9, "installation.mdx": __fd_glob_10, "quick-start.mdx": __fd_glob_11, "why-fluxy.mdx": __fd_glob_12, "components/avatar.mdx": __fd_glob_13, "components/bottom-bar.mdx": __fd_glob_14, "components/button.mdx": __fd_glob_15, "components/chart.mdx": __fd_glob_16, "components/dashboard.mdx": __fd_glob_17, "components/grid.mdx": __fd_glob_18, "components/image.mdx": __fd_glob_19, "components/layout.mdx": __fd_glob_20, "components/shimmer.mdx": __fd_glob_21, "components/tab-scaffold.mdx": __fd_glob_22, "components/table.mdx": __fd_glob_23, "feedback/badge.mdx": __fd_glob_24, "feedback/dialog.mdx": __fd_glob_25, "feedback/loader.mdx": __fd_glob_26, "feedback/modal.mdx": __fd_glob_27, "feedback/toast.mdx": __fd_glob_28, "ecosystem/cloud-builds.mdx": __fd_glob_29, "ecosystem/devtools.mdx": __fd_glob_30, "ecosystem/examples.mdx": __fd_glob_31, "ecosystem/i18n.mdx": __fd_glob_32, "ecosystem/networking.mdx": __fd_glob_33, "ecosystem/ota-engine.mdx": __fd_glob_34, "ecosystem/play.mdx": __fd_glob_35, "ecosystem/roadmap.mdx": __fd_glob_36, "ecosystem/routing.mdx": __fd_glob_37, "forms/checkbox-switcher.mdx": __fd_glob_38, "forms/dropdown.mdx": __fd_glob_39, "forms/form.mdx": __fd_glob_40, "forms/input.mdx": __fd_glob_41, "layout/alignment.mdx": __fd_glob_42, "layout/layout-spacing.mdx": __fd_glob_43, "layout/responsive-concepts.mdx": __fd_glob_44, "layout/responsive-design.mdx": __fd_glob_45, "layout/safe-ui.mdx": __fd_glob_46, "fundamentals/architecture.mdx": __fd_glob_47, "fundamentals/cli.mdx": __fd_glob_48, "fundamentals/core-concepts.mdx": __fd_glob_49, "fundamentals/data-layer.mdx": __fd_glob_50, "fundamentals/dependency-injection.mdx": __fd_glob_51, "fundamentals/fluxy-core.mdx": __fd_glob_52, "fundamentals/performance.mdx": __fd_glob_53, "fundamentals/reactive-engine.mdx": __fd_glob_54, "fundamentals/reactivity.mdx": __fd_glob_55, "fundamentals/state-management.mdx": __fd_glob_56, "fundamentals/testing.mdx": __fd_glob_57, "fundamentals/workflow.mdx": __fd_glob_58, "migration/index.mdx": __fd_glob_59, "migration/migration-0-1-10.mdx": __fd_glob_60, "migration/migration-0-1-11.mdx": __fd_glob_61, "migration/migration-0-1-6.mdx": __fd_glob_62, "migration/migration-0-1-7.mdx": __fd_glob_63, "migration/migration-0-1-8.mdx": __fd_glob_64, "migration/migration-0-1-9.mdx": __fd_glob_65, "migration/migration-0-2-0.mdx": __fd_glob_66, "migration/migration-0-2-1.mdx": __fd_glob_67, "migration/migration-0-2-2.mdx": __fd_glob_68, "migration/migration-0-2-3.mdx": __fd_glob_69, "migration/migration-0-2-4.mdx": __fd_glob_70, "style/core-primitives.mdx": __fd_glob_71, "style/motion.mdx": __fd_glob_72, "style/theme.mdx": __fd_glob_73, "style/tokens.mdx": __fd_glob_74, "style/ui-dsl.mdx": __fd_glob_75, });